version: "3.8"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: inventory
      NODE_ENV: development
    command: npm run start:dev

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000" # Host:Container port
  #   volumes:
  #     - ./frontend:/app # Sync local code
  #     - /app/node_modules # Isolate container's node_modules
  #   environment:
  #     - NODE_ENV=development
  #     - CHOKIDAR_USEPOLLING=true # Required for file watching in Docker
  #   command: sh -c "npm install && npm start"
  #   stdin_open: true # Needed for React's interactive dev server

volumes:
  postgres_data:
