version: "3.8"
services:
  db:
    image: postgres:latest
    env_file: ./backend/.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: modish-log-backend
    build:
      context: ./backend
      target: development
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - NODE_ENV=development

  frontend:
    container_name: modish-log-frontend
    build:
      context: ./frontend
      target: development
    ports:
      - "3002:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

volumes:
  postgres_data:
