services:
  # Backend API service
  - type: web
    name: modish-log-api
    region: oregon
    plan: free
    runtime: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && node dist/main.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: modish-log-acceptance-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 1h
      - key: PORT
        value: 3001


  # Database service
databases:
  - name: modish-log-acceptance-db
    region: oregon
    plan: free
