FROM node:14-alpine

WORKDIR /app

COPY package*.json ./app

RUN npm install
# RUN npm rebuild bcryptjs --build-from-source

COPY . /app

EXPOSE 3000

RUN npm run build
# Run app
CMD ["npm", "run", "start:dev"]

