version: "3.8"

services:
  db:
    image: postgres:13-alpine
    # restart: always
    ports:
      - '5432:5432'
    # env_file:
    #   - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    # networks:
    #   - nest-init
    environment:
      - POSTGRES_DB=modish
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
    #   - PGUSER=postgres
    # healthcheck:
    #   test: [ "CMD-SHELL", "pg_isready" ]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
  

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - /usr/app/node_modules
    ports:
      - '3001:3001'
    environment:
      - POSTGRES_DB=modish
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db


  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   container_name: nest-pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=pgadmin4
  #   ports:
  #     - '5050:80'
  #   depends_on:
  #     - modish-db

volumes:
   postgres:
      name: nest-modish-docker-db

# networks:
#    nest-init:

