name: Deploy
on: [push]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: railway/action@v1
        with:
          project: ${{ secrets.RAILWAY_PROJECT_ID }}
          service: ${{ secrets.RAILWAY_SERVICE_NAME }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      # - name: Run DB Migrations
      #   run: |
      #     railway run npm run migration:run
      #     docker run --rm -e DATABASE_URL=${{ secrets.DATABASE_URL }} your-railway-image npm run migration:run

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend
    steps:
      - uses: actions/checkout@v4
      - uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: frontend